#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd -P)
OH_MY_ZSH="$HOME"/.oh-my-zsh/
VUNDLE="$HOME"/.vim/bundle/Vundle.vim

cd $HOME

set -e

install_dotfiles() {
  echo "Installing dotfiles"

  for src in $(find -H "$DOTFILES_ROOT" -name '*.sym' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

link_file() {
  local src=$1 dst=$2
  local overwrite=true

  if [ "$overwrite" == "true" ]; then
    rm -rf "$dst"
    echo "Removed $dst"
  fi

  ln -s "$1" "$2"
  echo "Linked $1 to $2"
}

install_oh_my_zsh() {
  if [ ! -d "$OH_MY_ZSH" ]; then
    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  else
    echo "oh-my-zsh is already installed"
  fi
}

switch_to_zsh() {
  if [[ "$SHELL" =~ "zsh" ]]; then
    echo "Already using zsh"
  else
    chsh -s `which zsh`
    echo "Switched the default shell to zsh"
  fi
}

init_vundle() {
  if [ ! -f "$VUNDLE" ]; then
    git clone https://github.com/VundleVim/Vundle.vim.git "$VUNDLE"
    echo "Installed Vundle"
  fi

  vim +PluginInstall +qall
}

copy_file() {
  local src=$1 dst=$2
  local overwrite=true

  if [ "$overwrite" == "true" ]; then
    cp -rf "$src" "$dst"
    echo "Copied $src to $dst"
  fi
}

install_oh_my_zsh
switch_to_zsh
install_dotfiles
init_vundle
copy_file "$DOTFILES_ROOT"/zsh/aliases.zsh "$OH_MY_ZSH"/custom/

echo "All installed"
